Improve application category detection
cairoshell/ManagedShell pull request #14
Opened 2021-05-04 19:06 UTC by kevinboss

Detect category by comparing ProcId of already open windows with new window
Detect category by comparing executable (adds category detection when application is launched via symlink, for example scoop apps)

2021-05-11 23:01 UTC, dremin requested changes
Thanks! Some minor changes requested but nothing major.

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
> +        {
I think a string comparison before performing file IO might be a worthwhile optimization-- return true if path1 == path2.

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
> +using Microsoft.Win32.SafeHandles;
Unneeded using

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
> +                    var result2 = NativeMethods.GetFileInformationByHandle(sfh2, out fileInfo2);
Nit: `NativeMethods.` is inconsistent/redundant here

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
> +                        throw new IOException(string.Format("GetFileInformationByHandle has failed on {0}", path1));
Rather than throwing here (and below) could you use ShellLogger?

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.WindowsTasks/ITaskCategoryProvider.cs
> +using System.Collections.ObjectModel;
I don't believe these are necessary.

2021-05-11 23:01 UTC, dremin commented on src/ManagedShell.WindowsTasks/Tasks.cs
> +        public ICollection<ApplicationWindow> Windows => _tasksService.Windows;
The GroupedWindows collection view filters out windows that are not shown in the taskbar (which is the majority of windows). I'd rather not add a facility to bypass this. Looking at the corresponding cairoshell changes, you should be able to loop through GroupedWindows as-is without adding this new property.

2021-05-12 15:56 UTC, dremin requested changes
Looks good! Ready to merge once that leftover `using` is removed.

2021-05-12 15:56 UTC, dremin commented on src/ManagedShell.WindowsTasks/Tasks.cs
> +using System.Collections.Generic;
I believe this is unnecessary now that the generic collection was removed.

2021-05-12 17:37 UTC, kevinboss commented on src/ManagedShell.WindowsTasks/Tasks.cs
> +using System.Collections.Generic;
I am terrible when it comes to unused usings...thanks for spotting that :)

2021-05-12 17:39 UTC, dremin approved these changes
🎉

2021-05-12 17:39 UTC, merged