Add LayoutHelper
cairoshell/ManagedShell pull request #53
Opened 2022-03-04 18:38 UTC by curoviyxru

2022-03-05 20:42 UTC, dremin requested changes
Thanks for adding this much-needed functionality! Added some suggestions to help make it easier to consume.

2022-03-05 20:42 UTC, dremin commented on src/ManagedShell.Common/Helpers/LayoutHelper.cs
> +    public static class LayoutHelper
This name is a bit ambiguous, maybe one of these options would be a bit better?

- KeyboardLayoutHelper
- KeyboardHelper
- InputHelper
- LocaleHelper

2022-03-05 20:42 UTC, dremin commented on src/ManagedShell.Common/Helpers/LayoutHelper.cs
> +            return NativeMethods.GetKeyboardLayout(currentThread ? 0 : NativeMethods.GetWindowThreadProcessId(NativeMethods.GetForegroundWindow(), out _));
I noticed you grabbed the display names for these in Cairo code. I think it would be useful to do that in this class instead so that the consuming shell doesn't need to know how. Maybe return a struct that has an ID and Name property?

2022-03-05 20:42 UTC, dremin commented on src/ManagedShell.Common/Helpers/LayoutHelper.cs
> +            return result;
Same as above, but a list

2022-03-05 21:29 UTC, curoviyxru commented on src/ManagedShell.Common/Helpers/LayoutHelper.cs
> +            return NativeMethods.GetKeyboardLayout(currentThread ? 0 : NativeMethods.GetWindowThreadProcessId(NativeMethods.GetForegroundWindow(), out _));
yeah, I'll do it now

2022-03-05 21:30 UTC, curoviyxru commented on src/ManagedShell.Common/Helpers/LayoutHelper.cs
> +    public static class LayoutHelper
i like `KeyboardLayoutHelper` the most

2022-03-06 00:01 UTC, dremin approved these changes
🎉

2022-03-06 00:01 UTC, merged