Misc updates
cairoshell/ManagedShell pull request #96
Opened 2024-02-25 08:11 UTC by xoascf

2024-02-26 02:06 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
Should I restore them and mark them as obsolete?

2024-02-27 02:51 UTC, dremin requested changes

2024-02-27 02:51 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
As far as I can tell in my testing, the behavior does not change to be a toggle, it still only shows. I think the old name should probably remain.

2024-02-27 02:51 UTC, dremin commented on src/ManagedShell.Common/Helpers/KeyboardLayoutHelper.cs
> +            return new KeyboardLayout((uint)layout);
We should add some sort of check that `layout >= 0` to handle dremin/RetroBar#758. The same also applies to the `GetKeyboardLayoutList` method.

2024-02-27 02:51 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
I notice there is no more version check, does this work on Windows 10?

2024-02-27 07:50 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
> I notice there is no more version check, does this work on Windows 10?

There is no need to do the checking here, the developer should know when and where to use this.

2024-02-27 07:54 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
> As far as I can tell in my testing, the behavior does not change to be a toggle, it still only shows. I think the old name should probably remain.

It works fine for me on Windows 10 and in a Windows 11 VM with a RetroBar build with these changes. I haven't tested it with Cairo Shell, but I assumed it would work the same...

2024-02-27 07:55 UTC, xoascf commented on src/ManagedShell.Common/Helpers/KeyboardLayoutHelper.cs
> +            return new KeyboardLayout((uint)layout);
Hmm, OK.

2024-02-27 08:57 UTC, xoascf commented on src/ManagedShell.Common/Helpers/KeyboardLayoutHelper.cs
> +            return new KeyboardLayout((uint)layout);
But casting it to `uint` already does this, it shouldn't be a problem since the value is always positive, otherwise we could catch any kind of exception and use English (`1033`) as a fallback.

2024-02-27 22:43 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
https://github.com/cairoshell/ManagedShell/pull/96/commits/3bfbace4c60542f487c7e60264c4a95470fb2a45 fixes the `WM.HOTKEY` handling for `Shell_TrayWnd`, that way we don't need to notify all top-level windows.

2024-02-27 23:08 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
@dremin, can you think of a way to send messages directly to `Shell_TrayWnd` instead of using the custom AppBar wrapper/forwarder, so there is no need to play around with it internally?

2024-02-28 00:28 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
@xoascf `WindowHelper.FindWindowsTray` accepts an `ignoreHwnd` parameter that you can pass the ManagedShell tray's hwnd to, it is intended for this purpose. The simplest way to implement this is probably to have the shell pass that hwnd to `ShowActionCenter` etc, otherwise there would be a circular dependency.

2024-02-28 05:05 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
It works now... at least for me.

2024-02-29 02:43 UTC, xoascf commented on src/ManagedShell.WindowsTray/NotifyIcon.cs
> +                    ShellHelper.ToggleActionCenter();
This is now unresponsive, just tested with this PR in RetroBar, maybe this should be handled externally and not here.

2024-03-13 04:00 UTC, dremin requested changes

2024-03-13 04:00 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
I am still seeing the same behavior as the original code--it is not a toggle. What are the intended effects of the changes?

2024-03-13 16:06 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
It works perfectly for me, this on a clean install of Windows 10 and Windows 11.

2024-03-14 20:44 UTC, xoascf commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
The version commented here should work: https://github.com/dremin/RetroBar/issues/758#issuecomment-1973263298

2024-03-15 04:25 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
On that build for me the notification center works as a toggle, but the action center is not working as a toggle.

2024-05-29 00:49 UTC, dremin commented on src/ManagedShell.Common/Helpers/ShellHelper.cs
>          }
I believe what causes this to act as a toggle vs. 'always show' is whether or not focus is stolen as part of the click but before the hotkey is sent. If the shell either sets noactivate, or sends the hotkey on mousedown instead of mouseup, it seems to work with existing ManagedShell functions. Are you able to confirm this? If so, I believe the existing code for those functions should be restored, as the 'toggle' behavior is ultimately achieved by the shell app, not ManagedShell.

2025-01-01 09:04 UTC, closed without merging